### ISSUE TITLE
Error compiling

### ISSUE THREAD

**Issue by ricadelic** [cminyard/gensio#1]
When i try to compile the library i recieve the following error:
(i ran autoreconf -i, then ./configure)

[23:39:36] root@domotica-03:/opt/gensio# make
Making all in .
make[1]: Entering directory '/opt/gensio'
  CC       gensio_ssl.lo
gensio_ssl.c:314:1: error: conflicting types for 'ssl_gensio_accepter_alloc'
 ssl_gensio_accepter_alloc(char *args[],
 ^~~~~~~~~~~~~~~~~~~~~~~~~
In file included from ./include/gensio/gensio_class.h:24:0,
                 from gensio_ssl.c:22:
./include/gensio/gensio.h:769:5: note: previous declaration of 'ssl_gensio_accepter_alloc' was here
 int ssl_gensio_accepter_alloc(struct gensio_accepter *child, char *args[],
     ^~~~~~~~~~~~~~~~~~~~~~~~~
Makefile:556: recipe for target 'gensio_ssl.lo' failed
make[1]: *** [gensio_ssl.lo] Error 1
make[1]: Leaving directory '/opt/gensio'
Makefile:578: recipe for target 'all-recursive' failed
make: *** [all-recursive] Error 1
[23:39:39] root@domotica-03:/opt/gensio#

**Comment by cminyard** [comment]
On 12/13/18 4:40 PM, Rick Jongbloed wrote:
>
> When i try to compile the library i recieve the following error:
> (i ran autoreconf -i, then ./configure)
>
Wow, I didn't expect anyone to be using this yet.  It is still somewhat 
a work in progress, there may be API changes still coming.

I just pushed up everything I have, which compiles and passes all 
tests.  Hopefully that helps.

-corey
