### ISSUE TITLE
gensio should have a way to disable man page installation

### ISSUE THREAD

**Issue by jameshilliard** [cminyard/gensio#14]
As gensio/ser2net is frequently used on embedded systems there should be a way to disable man page installation in autoconf to reduce the installed size.

**Comment by cminyard** [comment]
On Sat, Apr 11, 2020 at 12:37:52PM -0700, James Hilliard wrote:
> As gensio/ser2net is frequently used on embedded systems there should be a way to disable man page installation in autoconf to reduce the installed size.

There are a number of things that you don't want to install on an
embedded system, like the .a files, include files, some .so links.

However, I don't know of an easy way to do this from the configure/make
files.  There are some hacks you could do, like changing all the
directories for man/include/etc in the configure to be some common place
and then deleting them after the install.  I'm pretty sure that cmake
can't do it, either.

The way this is normally done is you use rpm/dpkg/yocto/... to build it,
and those take care of packaging up the pieces into logical packages.
I'm not sure what build system you are using, but that should be the
place to look for this functionality.

-corey

**Comment by jameshilliard** [comment]
> There are a number of things that you don't want to install on an
embedded system, like the .a files, include files, some .so links.

generally those should have some sort of conditional install in that case, usually via configure flags or cmake equivalents

> However, I don't know of an easy way to do this from the configure/make
files.  There are some hacks you could do, like changing all the
directories for man/include/etc in the configure to be some common place
and then deleting them after the install.  I'm pretty sure that cmake
can't do it, either.

Oh, it's absolutely possible with both autotools and cmake, I'll spin up an autotools patch adding a configure flag disabling man pages as an example for how it's often done, in fact most embedded build systems rely on the upstream packages having flags to disable man/tests and so forth as they generally try to avoid patching the upstream package.

> The way this is normally done is you use rpm/dpkg/yocto/... to build it,
and those take care of packaging up the pieces into logical packages.
I'm not sure what build system you are using, but that should be the
place to look for this functionality.

So I'm using buildroot which doesn't generate rpm/dpkg style packages but rather builds packages from source and installs them into a rootfs image.

**Comment by cminyard** [comment]
This is in and released.
