### ISSUE TITLE
GCC10 build error

### ISSUE THREAD

**Issue by yegorich** [cminyard/gensio#17]
GCC complains about the multiple definition of `localport_err`:

```
arm-buildroot-linux-gnueabihf/bin/ld: libgensiotool.a(localports.o):(.bss+0xc): multiple definition of `localport_err'; gtlssh.o:(.bss+0x24): first defined here
collect2: error: ld returned 1 exit status
```

**Comment by cminyard** [comment]
Dang, I just did a release yesterday.  This always happens :-).

It was a missing extern in the include file; I have pushed up a fix to git.  Thanks for reporting this.  I'm not sure why earlier linkers didn't complain.
