### ISSUE TITLE
debian error compiling gensio_ll_ipmisol.c

### ISSUE THREAD

**Issue by alfonsius** [cminyard/gensio#2]
debian 9.9 4.9.0-9-amd64
gensio_ll_ipmisol.c:1261:13: error: ‘ipmi_con_t {aka struct ipmi_con_s}’ has no member named ‘disable’ solll->ipmi->disable(solll->ipmi);

./configure --with-openipmi=no compiles fine

dpkg -l | grep ii | grep ipmi

ii  freeipmi-common                       1.4.11-1.1+b1                      amd64        GNU implementation of the IPMI protocol - common files
ii  libfreeipmi-dev                       1.4.11-1.1+b1                      amd64        GNU IPMI - development package
ii  libfreeipmi16                         1.4.11-1.1+b1                      amd64        GNU IPMI - libraries
ii  libopenipmi-dev                       2.0.22-1.1                         amd64        Intelligent Platform Management Interface - development
ii  libopenipmi0                          2.0.22-1.1                         amd64        Intelligent Platform Management Interface - runtime
ii  openipmi                              2.0.22-1.1                         amd64        Intelligent Platform Management Interface (for servers)

**Comment by cminyard** [comment]
On Thu, Jul 04, 2019 at 07:41:50AM -0700, alfonsius wrote:
> debian 9.9 4.9.0-9-amd64
> gensio_ll_ipmisol.c:1261:13: error: ‘ipmi_con_t {aka struct ipmi_con_s}’ has no member named ‘disable’ solll->ipmi->disable(solll->ipmi);

You need to get the newest version of the OpenIPMI library installed.

-corey

**Comment by alfonsius** [comment]
thank you very much for your fast answer
have a nice day
