### ISSUE TITLE
no manpage for gensiot

### ISSUE THREAD

**Issue by Zugschlus** [cminyard/gensio#22]
Hi,

while the geniso source contains man pages for library functions and configuration files, the manual page for /usr/bin/gensiot seems to be missing.

Greetings
Marc

**Comment by cminyard** [comment]
There is a man page for gensiot, it's in the tools directory where gensiot exists, not in the man directory, and it seems to be installed in my tests.  Are you not seeing this?

-corey

**Comment by Zugschlus** [comment]
I am sorry, I didn't look hard enough. The page is there.
