### ISSUE TITLE
Support: Cross compile gensio lib for Windows

### ISSUE THREAD

**Issue by AEberleMW** [cminyard/gensio#25]
In order to implement a Windows client for connecting to ser2net using certauth I try to build a Windows library of gensio. I did the following steps (on a recent debian testing installation) but make always fails with serveral compilation erroros:

1. Checkout tag v.2.2.4
2. Run ``autoreconf -i``
3. Run configure using mingw as target and host: ``./configure --target=i686-w64-mingw64 --host=i686-w64-mingw64 --without-python --without-swig``
4. Run ``make``
5. Compilation error, e.g.
```
gensio_osops.c:17:10: fatal error: termios.h: Datei oder Verzeichnis nicht gefunden
   17 | #include <termios.h>
      |          ^~~~~~~~~~~
compilation terminated.
```

I think there is something wrong with my configure command. Do you have any suggestions how to correctly cross compile the lib for Windows?

**Comment by cminyard** [comment]
On Wed, Mar 03, 2021 at 12:47:32AM -0800, Marco Wenzel wrote:
> In order to implement a Windows client for connecting to ser2net using certauth I try to build a Windows library of gensio. I did the following steps (on a recent debian testing installation) but make always fails with serveral compilation erroros:
> 
> 1. Checkout tag v.2.2.4
> 2. Run ``autoreconf -i``
> 3. Run configure using mingw as target and host: ``./configure --target=i686-w64-mingw64 --host=i686-w64-mingw64 --without-python --without-swig``
> 4. Run ``make``
> 5. Compilation error, e.g.
> ```
> gensio_osops.c:17:10: fatal error: termios.h: Datei oder Verzeichnis nicht gefunden
>    17 | #include <termios.h>
>       |          ^~~~~~~~~~~
> compilation terminated.
> ```
> 
> I think there is something wrong with my configure command. Do you have any suggestions how to correctly cross compile the lib for Windows?

Well, you aren't going to be able to use Unix things when compiling for
a Windows target, no amount of configuring is going to fix that.  You
might get it to work compiling under the msys2 environment and not cross
compiling, IIRC I tried it and it sort of works, but then it's not
native Windows.

I have been working on Windows support, though.  There is also full C++
support, Windows and Linux.  I've been looking for a
victim^H^H^H^H^H^Huser to try it out.  You can check out the master
branch and it should work, or you can compile under Visual Studio.  I
haven't spent much time on how to "install" things from Visual Studio
or msys64 into a native Windows environment.  (Any help would be
appreciated.)

The programs produced are Windows native command line apps, so they
don't run very well under the msys environment.

I have some of the testing working, but there are likely to still be
some issues.  SSL/certauth is not working yet.  Integrating in the
openssl library on Windows should work, but I was looking at using the
native Windows SSL interfaces.  That shouldn't be terribly hard, but I
haven't spent much time on it.  I'm getting strange issues with the UDP
tests.  But basic tcp, serialdev, stdio, and all the filter gensios
except SSL and certauth seem to work.

-corey

**Comment by AEberleMW** [comment]
Thank you for the hints! Building with wsys2 worked fine and I produced some executables and a DLL.

Since certauth and SSL currently won't work, this solution will not applicable for us. But maybe we can work together in order to make it run. I have to clear it up with my company.

Another question in this context: Do you think it is possible to implement PAM authentication as certauth option on Linux? I successfully tested it with gtlsshd. We want to use it in a similar way with ser2net in order to establish a secure password (local and RADIUS) authenticated connection.

Thanks,
Marco

**Comment by cminyard** [comment]
On Thu, Mar 04, 2021 at 11:18:18PM -0800, Marco Wenzel wrote:
> Thank you for the hints! Building with wsys2 worked fine and I produced some executables and a DLL.
> 
> Since certauth and SSL currently won't work, this solution will not applicable for us. But maybe we can work together in order to make it run. I have to clear it up with my company.

There are two options here.  I know windows versions of openssl are
avaiable, but I haven't spent any time looking at them.  My preferred
solution would be to use native Windows crypto for this.  I spent a
little time looking at it last night.  It doesn't look terrible, but it
would be a bit of work and the key management is quite a bit different.

I'm not a Windows expert by any means, I'm just learning.  If you have
Windows expertise to apply to this, especially in crypto, that would be
very helpful.

> 
> Another question in this context: Do you think it is possible to implement PAM authentication as certauth option on Linux? I successfully tested it with gtlsshd. We want to use it in a similar way with ser2net in order to establish a secure password (local and RADIUS) authenticated connection.

I'd prefer to keep certauth more "pure", but it might be possible to
implement something on top certauth, like a library or another gensio.
I'm guessing what you are looking for is something that would do all the
certificate/password authentication and report a new connection when
authentication completes successfully, right?  That would allow you to
use local logins for ser2net authentication, which might be nice.

-corey

**Comment by cminyard** [comment]
On Thu, Mar 04, 2021 at 11:18:18PM -0800, Marco Wenzel wrote:
> Thank you for the hints! Building with wsys2 worked fine and I produced some executables and a DLL.
> 
> Since certauth and SSL currently won't work, this solution will not applicable for us. But maybe we can work together in order to make it run. I have to clear it up with my company.

Actually, I just looked and SSL compiles under mingw64 if you install
the openssl libraries.  That should work if you don't need native
windows crypto support.

I assume it's still using directories and files to hold keys and
certificates, not the Windows crypto store.

-corey

**Comment by AEberleMW** [comment]
> There are two options here. I know windows versions of openssl are avaiable, but I haven't spent any time looking at them. My preferred solution would be to use native Windows crypto for this. I spent a little time looking at it last night. It doesn't look terrible, but it would be a bit of work and the key management is quite a bit different. I'm not a Windows expert by any means, I'm just learning. If you have Windows expertise to apply to this, especially in crypto, that would be very helpful.

We also do not have that much expertise in Windows. But I think initially the OpenSSL (certificates in files...) variant could be sufficient.

> Another question in this context: Do you think it is possible to implement PAM authentication as certauth option on Linux? I successfully tested it with gtlsshd. We want to use it in a similar way with ser2net in order to establish a secure password (local and RADIUS) authenticated connection.
> I'd prefer to keep certauth more "pure", but it might be possible to implement something on top certauth, like a library or another gensio. I'm guessing what you are looking for is something that would do all the certificate/password authentication and report a new connection when authentication completes successfully, right? That would allow you to use local logins for ser2net authentication, which might be nice.

This is correct. What we want is an encrypted TCP connection to ser2net for authenticated users. The crypto should be SSL/TLS, sharing certificates/keys with the webserver on the same machine and the authentication should use PAM in order to enable local authentication and optionally RADIUS authentication. 

So your proposal sounds good and maybe we could implement a separate gensio named "pamauth" or something like that.

We are currently in discussion if this solution fits all our needs. I will let you know the results.

Regards,,
Marco

**Comment by cminyard** [comment]
On Mon, Mar 08, 2021 at 11:32:56PM -0800, Marco Wenzel wrote:
> > There are two options here. I know windows versions of openssl are avaiable, but I haven't spent any time looking at them. My preferred solution would be to use native Windows crypto for this. I spent a little time looking at it last night. It doesn't look terrible, but it would be a bit of work and the key management is quite a bit different. I'm not a Windows expert by any means, I'm just learning. If you have Windows expertise to apply to this, especially in crypto, that would be very helpful.
> 
> We also do not have that much expertise in Windows. But I think initially the OpenSSL (certificates in files...) variant could be sufficient.

FYI, I just got gtlssh working, mostly, on Windows under Mingw64.  So
ssl and certauth seem to be working fine.

There are still issues with key handling; I really need gtlssh-keygen
working and since it's currently a shell script, obviously it's not.
But it shouldn't be too hard to translate.

> 
> > Another question in this context: Do you think it is possible to implement PAM authentication as certauth option on Linux? I successfully tested it with gtlsshd. We want to use it in a similar way with ser2net in order to establish a secure password (local and RADIUS) authenticated connection.
> > I'd prefer to keep certauth more "pure", but it might be possible to implement something on top certauth, like a library or another gensio. I'm guessing what you are looking for is something that would do all the certificate/password authentication and report a new connection when authentication completes successfully, right? That would allow you to use local logins for ser2net authentication, which might be nice.
> 
> This is correct. What we want is an encrypted TCP connection to ser2net for authenticated users. The crypto should be SSL/TLS, sharing certificates/keys with the webserver on the same machine and the authentication should use PAM in order to enable local authentication and optionally RADIUS authentication. 
> 
> So your proposal sounds good and maybe we could implement a separate gensio named "pamauth" or something like that.
> 
> We are currently in discussion if this solution fits all our needs. I will let you know the results.

Ok, sounds good.

-corey

**Comment by AEberleMW** [comment]
@cminyard Just to send a sign of life: We are still in a planning/discussion state. The customer requirements are complex and we want to have a sustainable solution. Currently it looks like we want to implement the PAM support. I will inform you when I know more.

**Comment by cminyard** [comment]
Any news on this?  It's been a while.

**Comment by AEberleMW** [comment]
Hi @cminyard,

for the same reasons like in [#26](https://github.com/cminyard/gensio/issues/26#issuecomment-1019807552) I would appreciate it when we could leave this issue open until we resume the work on it.

Best,
Marco

**Comment by AEberleMW** [comment]
HI @cminyard,

sorry again for the huge delay. I just went back to this topic now and started again to set up an build environment with [mingw](https://www.mingw-w64.org) to get some Windows binaries. 

The linker currently complains, that I do not have a shared version of libssl and libcrypto. How did you solve this? The mingw packaes of openssl are already installed.

Thanks,
Marco

**Comment by cminyard** [comment]
On Mon, Sep 12, 2022 at 03:04:00AM -0700, Marco Wenzel wrote:
> HI @cminyard,
> 
> sorry again for the huge delay. I just went back to this topic now and started again to set up an build environment with [mingw](https://www.mingw-w64.org) to get some Windows binaries. 
> 
> The linker currently complains, that I do not have a shared version of libssl and libcrypto. How did you solve this? The mingw packaes of openssl are already installed.

I don't remember seeing that problem.  Here's what I have installed:

***@***.*** MINGW64 ~
$ pacman -Q | grep openssl
libopenssl 1.1.1.q-1
mingw-w64-x86_64-openssl 1.1.1.q-1
openssl 1.1.1.q-1

You might have to have the main openssl installed, too.

Also, make sure you are building from the mingw64 login, not the msys2
login.

Other than that, I'm not sure.

-corey

**Comment by AEberleMW** [comment]
Sorry, it was my fault because I used the wrong environment. After setting up everything correctly the build works fine now. I already tested the gtlssh client and everything works as expected.

One additional question: I'd like to set up an automated Github build job with Github actions according to the [msys2 documentation](https://www.msys2.org/docs/ci/). Do you think it is reasonable to put the workflow YAML directly to the gensio repository?

**Comment by AEberleMW** [comment]
> That shouldn't be a problem. I've been looking at doing this, and I have a little automation, but it's obviously incomplete. I just don't know much about devops and how it all works. Something I need to spend some time on. Thanks,

Thank you, @cminyard. I will try to implement it and make a PR.

**Comment by AEberleMW** [comment]
> Thank you, @cminyard. I will try to implement it and make a PR.

I have a local branch with a CI job which works pretty well now. How should I contribute? Pushing seems to be not allowed for me.

**Comment by cminyard** [comment]
On Thu, Sep 15, 2022 at 06:14:31AM -0700, Marco Wenzel wrote:
> > Thank you, @cminyard. I will try to implement it and make a PR.
> 
> I have a local branch with a CI job which works pretty well now. How should I contribute? Pushing seems to be not allowed for me.

You can create a copy of the project, do your changes, and request a
merge.  Will that work?

Thanks,

-corey

**Comment by AEberleMW** [comment]
So everything worked fine and the PR is merged. Again thanks for your support!
