### ISSUE TITLE
Tag v2.2.6 was not found in any branch.

### ISSUE THREAD

**Issue by zangrc-fnst** [cminyard/gensio#27]
$ git tag --contains 2db44eec9e22efbc734bcae24d9f82b7ff2079d2
v2.2.6 
$ git branch -a --contains 2db44eec9e22efbc734bcae24d9f82b7ff2079d2

**Comment by cminyard** [comment]
On Wed, May 26, 2021 at 12:33:31AM -0700, zangrc-fnst wrote:
> $ git tag --contains 2db44eec9e22efbc734bcae24d9f82b7ff2079d2
> v2.2.6 
> $ git branch -a --contains 2db44eec9e22efbc734bcae24d9f82b7ff2079d2

Missed a push of the branch, it's fixed now.

Thanks,

-corey
