### ISSUE TITLE
Feature Request: Add Multicast TTL option

### ISSUE THREAD

**Issue by andrewwade** [cminyard/gensio#29]
Looks like multicast works great, (using ser2net). But I don't see an option for setting the Multicast TTL value. Am I missing it? I'm assuming it is set to 1 by default? 

It would be nice to be able to modify this value.
An example could be:

`udp(mcast=224.0.0.2,laddr='ipv4,3000',mttl=5),224.0.0.2,3000`

**Comment by cminyard** [comment]
Easy enough to add.

Well, I restructured a bunch of stuff that was sub-optimal about the socket interface, but with that done, adding mttl was easy.  It's on the master branch now.

**Comment by andrewwade** [comment]
Awesome! One comment, I think TTL max value is 255.
https://github.com/cminyard/gensio/blob/master/lib/gensio.c#L1992
