### ISSUE TITLE
Is there a udp option to make it read only or write only?

### ISSUE THREAD

**Issue by andrewwade** [cminyard/gensio#30]
I want to setup 3 different types of multicast connections:
 - Sender
 - Receiver
 - Peer (Sender and Receiver)
 
But I'm having a hard time configuring the yaml file in a way that allows each of these. Here's what I've found so far.

Send and receive on same multicast address:
 - Same as example in gensio manual   
   `accepter:conacc,udp(mcast=224.0.0.2,laddr='ipv4,3000',mloop=true,nocon=true,reuseaddr=true),224.0.0.2,3000`

Send only to multicast address:
- Setting nocon to false has the effect of not receiving anything from multicast group
   `accepter:conacc,udp(mcast=224.0.0.2,laddr='ipv4,3000',mloop=true,nocon=false,reuseaddr=true),224.0.0.2,3000`
- Setting readbuf to 0 also has the effect of not receiving anything from multicast group
   `accepter:conacc,udp(mcast=224.0.0.2,laddr='ipv4,3000',mloop=true,nocon=true,reuseaddr=true,readbuf=0),224.0.0.2,3000`
  
Receive only from multicast:
 - The best I could do is changing the destination port number, so sendto traffic doesn't go to the same address I'm receiving on. But its still sending somewhere which I don't want.
   `accepter: conacc, udp(mcast=224.0.0.2,laddr='ipv4,3000',mloop=true,nocon=true,reuseaddr=true),224.0.0.2,3001`
   

Neither the sender or receiver option is very straight forward. It would be nice to have `rdonly` and `wronly` flags that could be added in the UDP options. It would probably be useful for TCP as well. They should probably be mutually exclusive so you can't set both to true.

**Comment by cminyard** [comment]
On Thu, Jun 03, 2021 at 09:30:33AM -0700, Andrew Wade wrote:
> I want to setup 3 different types of multicast connections:
>  - Sender
>  - Receiver
>  - Peer (Sender and Receiver)
>  
> But I'm having a hard time configuring the yaml file in a way that allows each of these. Here's what I've found so far.
> 
> Send and receive on same multicast address:
>  - Same as example in gensio manual   
>    `accepter:conacc,udp(mcast=224.0.0.2,laddr='ipv4,3000',mloop=true,nocon=true,reuseaddr=true),224.0.0.2,3000`
> 
> Send only to multicast address:
> - Setting nocon to false has the effect of not receiving anything from multicast group
>    `accepter:conacc,udp(mcast=224.0.0.2,laddr='ipv4,3000',mloop=true,nocon=false,reuseaddr=true),224.0.0.2,3000`

I don't think you would want to set mcast in this case.  You don't have
to have a receive multicast socket to send to a multicast address.
You will still need mloop=true if any of the receivers are on the local
machine.

Setting nocon to false (the default, actually) will probably not do what
you want.  That just means it simulates connection-oriented things over
UDP.  So it's just ignoring packets except from the first thing it
received packets from.

> - Setting readbuf to 0 also has the effect of not receiving anything from multicast group
>    `accepter:conacc,udp(mcast=224.0.0.2,laddr='ipv4,3000',mloop=true,nocon=true,reuseaddr=true,readbuf=0),224.0.0.2,3000`

Yeah, that would do it :).  But it's going to initiate flow-control,
which would actually be ok on UDP, but not on TCP.

>   
> Receive only from multicast:
>  - The best I could do is changing the destination port number, so sendto traffic doesn't go to the same address I'm receiving on. But its still sending somewhere which I don't want.
>    `accepter: conacc, udp(mcast=224.0.0.2,laddr='ipv4,3000',mloop=true,nocon=true,reuseaddr=true),224.0.0.2,3001`

That's harder.  You could set the sending address to someplace bogus
(localhost,9999) but it still going to send there.

>    
> 
> Neither the sender or receiver option is very straight forward. It would be nice to have `rdonly` and `wronly` flags that could be added in the UDP options. It would probably be useful for TCP as well. They should probably be mutually exclusive so you can't set both to true.

Actually, I think it would be better to have those options on ser2net
itself and not on the individual gensios.  That's pretty easy.

-corey

**Comment by andrewwade** [comment]
For the receive only case, I can send traffic to localhost,9 since its the 'Discard Protocol' port. https://en.wikipedia.org/wiki/Discard_Protocol

I thought it would be equally useful as a gensio option similar to socat's UDP-RECVFROM, UDP-SENDTO, and UDP-DATAGRAM options. But for me it works to put those flags in ser2net since that's what I'm using gensio for. 

Thanks!

**Comment by andrewwade** [comment]
> I don't think you would want to set mcast in this case.  You don't have
> to have a receive multicast socket to send to a multicast address.
> You will still need mloop=true if any of the receivers are on the local
> machine.

I can't get this to work (removing mcast=) unless I keep `laddr='ipv4,3000'`. If I remove laddr or change the laddr port number, sent packets are not received by socat on the other end, but if I keep laddr set to port 3000, it binds to port 3000 so it still receives packets coming from socat.

Here is my setup:
```
  accepter: conacc, udp(laddr='ipv4,3000',mloop=true,nocon=true,reuseaddr=true),224.0.0.2,3000
  connector: stdio(self=true)
```
On another console (same machine) I have:
```
 socat UDP-DATAGRAM:224.0.0.2:3000,reuseaddr,ip-add-membership=224.0.0.2:eth0,ip-multicast-loop=1,bind=:3000 -
```

Am I missing something? Shouldn't I be able to set laddr to a different port number and still send to the multicast group on port 3000?

**Comment by cminyard** [comment]
On Thu, Jun 03, 2021 at 12:07:03PM -0700, Andrew Wade wrote:
> > I don't think you would want to set mcast in this case.  You don't have
> > to have a receive multicast socket to send to a multicast address.
> > You will still need mloop=true if any of the receivers are on the local
> > machine.
> 
> I can't get this to work (removing mcast=) unless I keep `laddr='ipv4,3000'`. If I remove laddr or change the laddr port number, sent packets are not received by socat on the other end, but if I keep laddr set to port 3000, it binds to port 3000 so it still receives packets coming from socat.
> 
> Here is my setup:
> ```
>   accepter: conacc, udp(laddr='ipv4,3000',mloop=true,nocon=true,reuseaddr=true),224.0.0.2,3000
>   connector: stdio(self=true)
> ```
> On another console (same machine) I have:
> ```
>  socat UDP-DATAGRAM:224.0.0.2:3000,reuseaddr,ip-add-membership=224.0.0.2:eth0,ip-multicast-loop=1,bind=:3000 -
> ```
> 
> Am I missing something? Shouldn't I be able to set laddr to a different port number and still send to the multicast group on port 3000?

On the receiving side, you have to set this but on the sending side it
doesn't matter.  If I run the following in one window:

  gensiot "udp(mcast=224.0.0.2,laddr='ipv4,3000',mloop,nocon,reuseaddr),224.0.0.2,3000"

and the following in the second window:

  gensiot "udp(mloop,reuseaddr),224.0.0.2,3000"

anything typed in the second window will appear in the first.  BTW, with
mloop, the first window will also receive anything it transmits.

To receive the packets, you have to have the port set to where the
sender will send to, so laddr= is required in the first window.  But
it's not required in the second window because it's not receiving any
packets.

-corey

**Comment by andrewwade** [comment]
Ah ok thanks for the example. It worked for me too. 

I must have something wrong in my socat command. I changed it to UDP-RECV and I was able to receive from the gensio with that configuration.

Thanks for the help!

**Comment by cminyard** [comment]
On Thu, Jun 03, 2021 at 02:11:47PM -0700, Andrew Wade wrote:
> Ah ok thanks for the example. It worked for me too. 
> 
> I must have something wrong in my socat command. I changed it to UDP-RECV and I was able to receive from the gensio with that configuration.
> 
> Thanks for the help!

No problem.  I have pushed a change into ser2net master that adds
no-con-to-acc and no-acc-to-con to disable data transfer in either
direction.  I think that will meet your needs better, as you suggested.

-corey
