### ISSUE TITLE
Feature Request: echo filter

### ISSUE THREAD

**Issue by mhei** [cminyard/gensio#37]
I've some RS-485 hardware which always echos back each byte which is actually sent out.
I'm wondering whether it could be implemented as additional, stackable filter or as option for serialdev?

**Comment by cminyard** [comment]
On Sun, Jan 09, 2022 at 03:12:17PM -0800, Michael Heimpold wrote:
> I've some RS-485 hardware which always echos back each byte which is actually sent out.
> I'm wondering whether it could be implemented as additional, stackable filter or as option for serialdev? 

I'm not sure I understand.  The current serialdev gensio supports
RS-485.  So you need something to suppress the echo?

-corey

**Comment by mhei** [comment]
Sorry for being that unprecise: the current RS-485 support in serialdev is fine.
Some RS-485 half-duplex adapters have e.g. switches to enable/disable local echo. This switches the Rx side between always-receiving or only-receive-when-not-sending. In the latter case, the "local echo" is suppressed by hardware.
Now I have a hardware, where I cannot disable this local echo. It hard-wired always on. That means, that I must handle this looped back Tx data on Rx side in software.
From high-level point of view it is just simple: when you transmit x bytes, then receive and discard the next x incoming bytes. (Optionally, one could compare both byte streams and if different, you know that transmission was disturbed, so reporting an error could make sense.)
While this can be also implemented on application level side, I think the library could also easily bring this as feature.

**Comment by cminyard** [comment]
On Sun, Jan 09, 2022 at 11:16:33PM -0800, Michael Heimpold wrote:
> Sorry for being that unprecise: the current RS-485 support in serialdev is fine.
> Some RS-485 half-duplex adapters have e.g. switches to enable/disable local echo. This switches the Rx side between always-receiving or only-receive-when-not-sending. In the latter case, the "local echo" is suppressed by hardware.
> Now I have a hardware, where I cannot disable this local echo. It hard-wired always on. That means, that I must handle this looped back Tx data on Rx side in software.
> From high-level point of view it is just simple: when you transmit x bytes, then receive and discard the next x incoming bytes. (Optionally, one could compare both byte streams and if different, you know that transmission was disturbed, so reporting an error could make sense.)
> While this can be also implemented on application level side, I think the library could also easily bring this as feature.


It's not quite so easy as this.  In face, I'm not sure it can be done
reliably.  Consider if it transmits the following:

  ABC

At the same time the following comes in:

  ABC123

and suppose the echo happens after the incoming data.  So the incoming
data will be:

  ABC123ABC

and the correct "ABC" to drop is the second one.  The trouble is, the
code has no way to know which "ABC" is the correct one to drop.

Once you get to the buffered level that gensio operates at, I can't
think of a way to implement this properly.  If the operation is
completely synchronous (you transmit a command, you get a response, and
no other data is ever received on the link) you can do it, but I don't
think it can be done generally, unless I'm missing something.

-corey

**Comment by mhei** [comment]
Ok, I understand your concern.
The setup is a RS-485 half-duplex connection.
That means, that only one transmitter can be active at the same time - otherwise
the electrical signal becomes garbage.
Another reduction is that the setup usually uses master slave protocols, e.g. Modbus. In other words, usually there are no unexpected/spontaneous/spurious transmissions: master requests, one slave responds. Only if master and slave(s) disagree (due to misconfiguration) about timeouts or similar, then a collision could happen.

However, I can imagine the following scenarios:
a) transmitting start at the very same time when another peer also starts to transmit
  a1) the peer's transmission is shorter or equal than our one -> our echoed back data differs from what we wanted to send (at least the first x bytes, tail might be equal) -> library detects this, discard data, optionally library can inform application that sending "failed" (in a setup which suppresses the echo in hardware, we would be blind and could not detect this at all at this level, so application would have to be prepared for it anyway)
  a2) the peer's transmission is longer than ours -> our echoed back data differs from what we wanted to send -> library detects this (see above) plus library passed additional rest data from input queue to
  application (which must be discard by application itself, e.g. due to higher-level timeout or CRC checks...)
b) transmitting started already and another peer starts its transmission while we are still sending;
  results in the same sub-scenarios as is a)
c) peer started transmission, we did not notice and started our transmission, too;
   depending on both transmission lengths, our transmission will disturb the peer's one
   partly, maybe "append" additional bytes to it (scenario you described); we cannot easily tell where our disturbance starts and what to drop; the only option I see is to empty out our own receiving buffer
   just before sending (or in other words: this data which was not yet passed from library to application), then we would receive the count of bytes we wanted to send, detect
   the garbage, discard it and the application might only receive the trailing garbage which in turn
   must be detected/discarded by application itself

So yes, the whole thing with RS-485 half-duplex is special
but applications must be prepared at some level to handle it.
The library would not make it worse.

BTW: Thanks for spending your time to discuss it, really appreciated.

**Comment by cminyard** [comment]
On Mon, Jan 10, 2022 at 03:18:07PM -0800, Michael Heimpold wrote:
> Ok, I understand your concern.
> The setup is a RS-485 half-duplex connection.
> That means, that only one transmitter can be active at the same time - otherwise
> the electrical signal becomes garbage.
> Another reduction is that the setup usually uses master slave protocols, e.g. Modbus. In other words, usually there are no unexpected/spontaneous/spurious transmissions: master requests, one slave responds. Only if master and slave(s) disagree (due to misconfiguration) about timeouts or similar, then a collision could happen.
> 
> However, I can imagine the following scenarios:

You are thinking about this at the level where you directly interact
with the hardware.  At that level you might be able to figure something
out, but that would be in the kernel, and even then I am skeptical.

The level where gensio works is above that.  For instance, there is no
way to say: Empty the receive buffer and don't let anything else into it
until I transmit some data and you get the echos.  All you are doing is
sending bytes and receiving bytes, you have no control of when the sends
or receives occur.  A program could start to send something, be
scheduled out, and a bunch of data comes in while it's scheduled out.

If this is a packet protocol, you could probably do something at the
packet level.  From what you describe, I would guess that's what you are
working with.  Otherwise I don't see how hardware like this could ever
be useful.  If that's the case, you can look at the packets and say
"This one is from me, discard it."  But you would be working with whole
packets at that point.  You could write a gensio layer to do this, but
it would be specific to your application, or at least this hardware
configuration.  Writing gensios isn't hard, at least for this sort of
thing, but there is a learning curve.  If you were going to do something
and use ser2net, then writing a gensio might be the best approach.  If
it's your own application, it's probably easier to just do it there,
unless you expect other uses of this.

/me is reminded that he was going to add a way to dynamically load
gensios with environment variables...

-corey

**Comment by mhei** [comment]
Yes, this was my original idea: implement such a filter in gensio so that I can use this library in my applications and also in ser2net. (The application only needs to implement a part of the whole peripheral commands etc. while during maintainance/reconfiguration etc. a technician would connect with his full-features Windows(tm) standard tool via ser2net - and I cannot modify this proprietary software so "patching" this echo away in the library was my approach).

> Writing gensios isn't hard, at least for this sort of thing, but there is a learning curve.

Ok, then I'll try to dig into this. Let's see how long it takes :smile:

**Comment by cminyard** [comment]
On Wed, Jan 12, 2022 at 12:16:34PM -0800, Michael Heimpold wrote:
> Yes, this was my original idea: implement such a filter in gensio so that I can use this library in my applications and also in ser2net. (The application only needs to implement a part of the whole peripheral commands etc. while during maintainance/reconfiguration etc. a technician would connect with his full-features Windows(tm) standard tool via ser2net - and I cannot modify this proprietary software so "patching" this echo away in the library was my approach).
> 
> > Writing gensios isn't hard, at least for this sort of thing, but there is a learning curve.
> 
> Ok, then I'll try to dig into this. Let's see how long it takes :smile: 

The easiest way to do this is to use the gensio_base code to do the hard
work for you so you can write the protocol code and some glue logic and
not worry about anything else.  It's suprisingly hard to handle some
things (mostly shutdown) in a multithreaded environment.

gensio_base has two main abstractions, a lower-level interface (ll) and
a filter.  The ll communicates with the gensio below (or to the actual
device at the bottom level), the filter does the data processing.

What you do is create the filter, like gensio_filter_msgdelim.[ch], the
implements the data processing.  Then you write something like
gensio_msgdelim.c, which glues the filter, the base code, and the ll all
together.  msgdelim is a gensio that converts a stream protocol to a
packet protocol, so it's probably a pretty good example.

-corey

**Comment by cminyard** [comment]
I think we determined that this wasn't really feasible.  I haven't heard anything in a while, so closing.
