### ISSUE TITLE
example for hot ssl certificate reload

### ISSUE THREAD

**Issue by edwardt** [cminyard/gensio#38]
Any example how to performa hot ssl certificate reload?
revoke the current ssl session and reestablish one with a new ssl cert?

**Comment by cminyard** [comment]
The gensio library doesn't expose a lot of capabilities of OpenSSL.  I'm not sure how to do this in OpenSSL, but if you can show that, I can add it to the SSL gensio.

**Comment by cminyard** [comment]
Closing on lack of response.
