### ISSUE TITLE
symbol visibility in C++

### ISSUE THREAD

**Issue by Zugschlus** [cminyard/gensio#44]
Hi,

I don't understand much of what I am writing now. gensio is my first library package that I am packaging for a distribution.

Debian writes (see [https://wiki.debian.org/UsingSymbolsFiles](https://wiki.debian.org/UsingSymbolsFiles)):

```
Proper visibility for C++ symbols

If your upstream is on board with this, they should be building with -fvisibility=hidden,
and decorate everything intentionally public with a macro that (when building with
gcc or clang) expands to __attribute__((__visibility__("default"))).

Some upstreams will be doing something similar already, because they are
portable to Windows and need to decorate public symbols with
__declspec(dllexport) on Windows. 
```

I at least dont see the -fvisibility=hidden setting in the gensio Makefiles, but I might be looking for the wrong thing. Can you please tell me whether you're already doing this and whether you would consider to do that to ease packaging. Thank you very much.

Greetings
Marc

**Comment by Zugschlus** [comment]
That was my choice, and corollary of my packaging of ser2net since 1.5 in 2001.

Thanks for looking into it. For completeness sake, I'm likely to drop the symbols file in the future again, but of course, having only the necessary symbols visible alsways helps.

**Comment by cminyard** [comment]
Ok, this is fixed.
