### ISSUE TITLE
need some example project

### ISSUE THREAD

**Issue by alexrayne** [cminyard/gensio#5]
Hallow!
library looks pretty, but it hard to though in without examle. i need telnet domain. If you have some simple implementation of it, could you provide such compilable sample?

**Comment by jameshilliard** [comment]
Well [ser2net](https://github.com/cminyard/ser2net) uses this library, have you looked at that?

**Comment by cminyard** [comment]
On Sat, Jan 25, 2020 at 03:13:08PM -0800, James Hilliard wrote:
> Well [ser2net](https://github.com/cminyard/ser2net) uses this library, have you looked at that?

That's a fairly complicated program.

The gensiotool program in the tools directory is simpler.  It was
originally meant as an example program.  It's going to be easier to
follow than ser2net.  But the code in (the badly named) ioinfo.c is
where the data transfer happens once things are set up, and it's kind of
complicated with all the serial port handling.

What kind of example are you looking for?  Are you accepting connections
or making connections?

-corey

**Comment by alexrayne** [comment]
i`ve solve my problem - just rewrite own bicycle, telnet is simple enough.
i seached framework suitable for embedded telnet server.  This lib looks good, but not trivial for use. 
tools/gltsshd - looks like example that i need, but it is complex too. and there os no enough doc - what it did. if you provide simpler version of gltsshd - without auth, it would be pretty for people that interest gensio.

**Comment by cminyard** [comment]
On Tue, Jan 28, 2020 at 02:10:22AM -0800, Alexander Lityagin wrote:
> i`ve solve my problem - just rewrite own bicycle, telnet is simple enough.
> i seached framework suitable for embedded telnet server.  This lib looks good, but not trivial for use. 

You never said what you were trying to do.  I agree some examples are a
good idea, and I could prioritize on what you were specifically looking
for.

> tools/gltsshd - looks like example that i need, but it is complex too. and there os no enough doc - what it did. if you provide simpler version of gltsshd - without auth, it would be pretty for people that interest gensio.

That would be gensiot.  The whole point of gtlsshd was for a proof of
concept of the authentication :).

You can do a lot with gensiot without writing any code.  Or you could
write a small program that just handles stdin/out and let gensiot hook
it to the network connection and handle telnet.

-corey

**Comment by cminyard** [comment]
Note that I have added some examples.  Feel free to extend them; licensing on them is loose.  And if you have any more examples in mind, feel free to write them and send them to me :).
