### ISSUE TITLE
tools/gtlsshd bug?

### ISSUE THREAD

**Issue by alexrayne** [cminyard/gensio#6]
inspects tools/gtlsshd.
at static void handle_new(.. found this :
`

    if (pw_login)
	certauth_args[2] = "enable-password";
    err = certauth_gensio_alloc(ssl_io, certauth_args, o,
				certauth_event, NULL, &certauth_io);
    if (err) {
	syslog(LOG_ERR, "Unable to allocate certauth gensio: %s",
	       gensio_err_to_str(err));
	exit(1);
    }

    err = gensio_open_nochild_s(certauth_io); 
`

looks if pw_login== false , certauth_io is not initialised, and have random pointer?

**Comment by cminyard** [comment]
I don't think so.  The
err = certauth_gensio_alloc(ssl_io, certauth_args, o,
			certauth_event, NULL, &certauth_io);
is not inside the "if (pw_login)" statement, so it's always runs, and if it doesn't return an error, certauth_io will always be set.

But maybe I'm not seeing what you are saying.  Feel free to re-open if I'm missing something.

Thanks,

-corey

**Comment by alexrayne** [comment]
yes, sure. 
this style - without identing code inside block confuses me.
