### ISSUE TITLE
Build system issues (pkgconfig files, overlinking)

### ISSUE THREAD

**Issue by kaechele** [cminyard/gensio#61]
I went down a bit of a rabbit hole trying to debug a build issue with ser2net I've been seeing on Fedora:

ser2net will not build unless `avahi-devel` is installed even though ser2net doesn't explicitly require it.

Curiously, the step that fails is the `AC_CHECK_LIB(yaml, yaml_document_initialize, [...])` step in ser2net's  `configure.ac`. And the reason for that is that the previous `PKG_CHECK_MODULES(GENSIOMDNS, libgensiomdns, [LIBS="$LIBS $GENSIOMDNS_LIBS"], [...])` step will pull in `libgensiomdns.pc` for information on how to build with `libgensiomdns`.

`libgensiomdns.pc` is generated from https://github.com/cminyard/gensio/blob/master/lib/libgensiomdns.pc.in.
The issue with this file is that it lists all its dependencies as `Libs`, instead of `Libs.private` or `Requires.private`. The result is that anything linking against `libgensiomdns` based on that pkgconfig file will also try linking against (among others) `-lavahi-client` even if nothing in the program being linked uses any symbols from there explicitly.
In the `configure` step of ser2net linking yaml will also try linking the stub test code `configure` tries to compile against `-lavahi-client`, necessitating the presence of `avahi-devel` for no other reason than not having that check fail.

The other issue this creates is that the resulting binaries will have unused direct dependencies. This is an issue with gensio as well, which I temporarily worked around in the Fedora build [using a hack](https://src.fedoraproject.org/rpms/gensio/blob/rawhide/f/gensio.spec#_116).

On a side note: I've recently embarked on learning about the [meson build system](https://mesonbuild.com) and have used the gensio project as my study object to try it out as I thought it'd be reasonably complex to be interesting but not overwhelming.
You can look at the work I've done so far here: https://github.com/kaechele/gensio/tree/meson It's still a mess, fairly incomplete and unorganized but it's just intended for my personal learning experience.

In doing that I've found some cruft in the current autotools setup that I intend to submit patches for, eventually. One example would be `libnsl` which I think is unused but still being looked for by autoconf. Or that https://github.com/cminyard/gensio/blob/master/lib/libgensioosh.pc.in suffers from some copypasta from `libgensiomdns`.

**Comment by cminyard** [comment]
On Sat, Jul 01, 2023 at 09:15:58AM -0700, Felix Kaechele wrote:
> I went down a bit of a rabbit hole trying to debug a build issue with ser2net I've been seeing on Fedora:
> 
> ser2net will not build unless `avahi-devel` is installed even though ser2net doesn't explicitly require it.
> 
> Curiously, the step that fails is the `AC_CHECK_LIB(yaml, yaml_document_initialize, [...])` step in ser2net's  `configure.ac`. And the reason for that is that the previous `PKG_CHECK_MODULES(GENSIOMDNS, libgensiomdns, [LIBS="$LIBS $GENSIOMDNS_LIBS"], [...])` step will pull in `libgensiomdns.pc` for information on how to build with `libgensiomdns`.
> 
> `libgensiomdns.pc` is generated from https://github.com/cminyard/gensio/blob/master/lib/libgensiomdns.pc.in.
> The issue with this file is that it lists all its dependencies as `Libs`, instead of `Libs.private` or `Requires.private`. The result is that anything linking against `libgensiomdns` based on that pkgconfig file will also try linking against (among others) `-lavahi-client` even if nothing in the program being linked uses any symbols from there explicitly.
> In the `configure` step of ser2net linking yaml will also try linking the stub test code `configure` tries to compile against `-lavahi-client`, necessitating the presence of `avahi-devel` for no other reason than not having that check fail.

Ok, that's a subtlety I missed.  I am not a packaging expert, so I try
to get by as I can.

So if you have a libgensio-dev package installed, but do not have
libavahi-client-dev installed, the libgensiomdms.pc.in will refer to
-lavahi-client, but it won't be there by default, and really isn't
necessary.  I have gone through all the pkg-config files and moved
things to Libs.private as necessary.

> 
> The other issue this creates is that the resulting binaries will have unused direct dependencies. This is an issue with gensio as well, which I temporarily worked around in the Fedora build [using a hack](https://src.fedoraproject.org/rpms/gensio/blob/rawhide/f/gensio.spec#_116).

Yeah, there are a lot of these.  I'm going to see if I can remove all
the unneeded dependencies.

> 
> On a side note: I've recently embarked on learning about the [meson build system](https://mesonbuild.com) and have used the gensio project as my study object to try it out as I thought it'd be reasonably complex to be interesting but not overwhelming.
> You can look at the work I've done so far here: https://github.com/kaechele/gensio/tree/meson It's still a mess, fairly incomplete and unorganized but it's just intended for my personal learning experience.

Does meson work on windows?  The gensio configuration is fairly
complicated, too, but meson can probably handle it.

I did have a cmake build system, but supporting two build systems is a
huge pain.  I know autoconf, so it sort of a path of least resistance
for me. 

> 
> In doing that I've found some cruft in the current autotools setup that I intend to submit patches for, eventually. One example would be `libnsl` which I think is unused but still being looked for by autoconf. Or that https://github.com/cminyard/gensio/blob/master/lib/libgensioosh.pc.in suffers from some copypasta from `libgensiomdns`.

Please so, though I'm working through some of this right now cleaning up
the pkg-config files.

Thanks,

-corey

**Comment by kaechele** [comment]
> Ok, that's a subtlety I missed. I am not a packaging expert, so I try to get by as I can.

No worries ;-) Most of this is new to me as well as I'm trying to improve my packaging skills.

> So if you have a libgensio-dev package installed, but do not have
libavahi-client-dev installed, the libgensiomdms.pc.in will refer to
-lavahi-client, but it won't be there by default, and really isn't
necessary.

Exactly.
The way the pkgconfig file is being interpreted by pkgconfig is basically telling the linker: If you want to link with me you'll also have to link yourself with avahi-client. 
This apparently is useful for libraries that cannot be used without another library (i.e. a library that supplies only supporting functions but needs to be used with functions of that underlying library so that it creates a direct dependency on it).
In this case `libgensiomdns` wraps avahi-client for us so that we aren't required to deal with it directly (i.e. I can write a program using `libgensiomdns` and never directly use a symbol from avahi-client).
A good indicator seems to be whether I have to include a header of the underlying library or if just using the main libraries' headers is good enough in my program.

I found this link useful regarding the pkgconfig format: https://people.freedesktop.org/~dbn/pkg-config-guide.html

I've also used these resources to understand this better:
- https://wiki.mageia.org/en/Overlinking_issues_in_packaging
- https://wiki.mageia.org/en/Underlinking_issues_in_packaging
- https://wiki.gentoo.org/wiki/Project:Quality_Assurance/As-needed

> Does meson work on windows?  The gensio configuration is fairly
complicated, too, but meson can probably handle it.

It does work on Windows and macOS as well. I do intend to test that eventually.

> I did have a cmake build system, but supporting two build systems is a
huge pain.  I know autoconf, so it sort of a path of least resistance
for me.


I agree, maintaining two build systems would not be worth it. The path of least resistance for you as the maintainer is the way to go.
As I mentioned, this meson thing is more a personal learning exercise for me. There is probably a lot of minutiae that the current autoconf setup has acquired from being developed and battle tested over many years that, right now, I'm failing to appreciate fully.
I really have no feelings regarding what ends up happening with the output of my little meson expedition once I'm done.
I hope it didn't come across as me saying autoconf is bad and in need of being ripped out and replaced and that my suggestions and findings regarding the current build system are helpful to improve gensio.

So far, I am finding meson needs a lot less boilerplate. But maybe that opinion may change once I get to the more intricate bits of the build system (eg. SWIG). I haven't even implemented the conditional parts of the build yet. As of now the branch I shared can only successfully build the libraries and tools with all dependencies present.

**Comment by cminyard** [comment]
On Sat, Jul 01, 2023 at 02:25:19PM -0700, Felix Kaechele wrote:
...
> 
> I found this link useful regarding the pkgconfig format: https://people.freedesktop.org/~dbn/pkg-config-guide.html
> 
> I've also used these resources to understand this better:
> - https://wiki.mageia.org/en/Overlinking_issues_in_packaging
> - https://wiki.mageia.org/en/Underlinking_issues_in_packaging
> - https://wiki.gentoo.org/wiki/Project:Quality_Assurance/As-needed

Thanks for the info.  I've updated things in git that hopefully make it
better.

> 
> > Does meson work on windows?  The gensio configuration is fairly
> complicated, too, but meson can probably handle it.
> 
> It does work on Windows and macOS as well. I do intend to test that eventually.
> 
> > I did have a cmake build system, but supporting two build systems is a
> huge pain.  I know autoconf, so it sort of a path of least resistance
> for me.
> 
> 
> I agree, maintaining two build systems would not be worth it. The path of least resistance for you as the maintainer is the way to go.

My big problem with cmake was that it was hard to figure out how to do
anything unusual.  I'd do it in autoconf, then spent five times as much
time trying to figure out how to do it in cmake.  It's really more of a
documentation issue than anything.  I split out the individual gensios
into their on .so files, and at that point I just gave up.  I added
cmake so it could be compiled in Visual C++, but mingw has been serving
my needs.

> As I mentioned, this meson thing is more a personal learning exercise for me. There is probably a lot of minutiae that the current autoconf setup has acquired from being developed and battle tested over many years that, right now, I'm failing to appreciate fully.
> I really have no feelings regarding what ends up happening with the output of my little meson expedition once I'm done.
> I hope it didn't come across as me saying autoconf is bad and in need of being ripped out and replaced and that my suggestions and findings regarding the current build system are helpful to improve gensio.
> 
> So far, I am finding meson needs a lot less boilerplate. But maybe that opinion may change once I get to the more intricate bits of the build system (eg. SWIG). I haven't even implemented the conditional parts of the build yet. As of now the branch I shared can only successfully build the libraries and tools with all dependencies present.

Well, I'm not against changing if it's equivalent and easier to
maintain.  I'm a qemu maintainer and they just switched to meson, and
it's pretty straightforward there.

Thanks,

-corey

**Comment by cminyard** [comment]
This should be fixed now.  Thanks for pointing this out and for the patches.

**Comment by yegorich** [comment]
Was playing with meson and came across this build error:

```
../lib/utils.c: In function ‘gensio_cntstr_free’:
../lib/utils.c:898:18: error: ‘struct gensio_os_funcs’ has no member named ‘str’
  898 |         o->free(o->str);
      |                  ^~
../lib/utils.c:898:9: error: too few arguments to function ‘o->free’
  898 |         o->free(o->str);
      |         ^
```

**Comment by cminyard** [comment]
> Was playing with meson and came across this build error:
> 
> ```
> ../lib/utils.c: In function ‘gensio_cntstr_free’:
> ../lib/utils.c:898:18: error: ‘struct gensio_os_funcs’ has no member named ‘str’
>   898 |         o->free(o->str);
>       |                  ^~
> ../lib/utils.c:898:9: error: too few arguments to function ‘o->free’
>   898 |         o->free(o->str);
>       |         ^
> ```

Ok, fixed.  Obviously, the o->free(o, str).  I guess CLang has GCC atomics set.  Thanks.
