### ISSUE TITLE
Looking for an example "drop in" application code to replace an existing "real" serial port.

### ISSUE THREAD

**Issue by chaudron** [cminyard/gensio#66]
I'm looking at replacing an existing application's _real_ serial port socket implementation with a remote ser2net serdev. This application uses a socket with read()/write() in combination with select() and poll().

What would be the best way to mimic this with the gensio library, allowing it to wait on data through poll() as a lot of other stuff is handled in the poll() loop?

I might not have looked good enough, but I could not find something in the examples.

**Comment by cminyard** [comment]
On Sun, Oct 08, 2023 at 12:54:54PM -0700, Eelco Chaudron wrote:
> I'm looking at replacing an existing application's _real_ serial port socket implementation with a remote ser2net serdev. This application uses a socket with read()/write() in combination with select() and poll().
> 
> What would be the best way to mimic this with the gensio library, allowing it to wait on data through poll() as a lot of other stuff is handled in the poll() loop?
> 
> I might not have looked good enough, but I could not find something in the examples.

The gensio library has something called "os funcs" that handles the
select()/poll() for you (with epoll() on Linux to improve performance,
and with Windows support).  It provides timers, ways to wait for
operations, locks, and of course, I/O in ways that are portable.

Basically, if you have a file descriptor, you call osfunc->add_iod()
to create an iod (IO descriptor) and then call osfunc->set_fd_handlers()
to set the functions that get called when you can read/write or when an
exception happens.  There are set_read_handler(), set_write_handler()
and set_except_handler() to enable/disable the various callbacks.  And
when you are done, clear_fd_handlers() shuts things down.

This type of thing can be overwhelming if you've never done something
like this, but if you have it's pretty straightforward.  It's common in
lots of interfaces, like glib, tcl, etc.  In fact, there are os funcs
already written on glib and tcl.

If you already have a framework like this, you can write your own OS
handler using it, but that can be a big job.  These sorts of things are
more subtle than you might imagine.

If you are multi-threaded, you can run the standard OS handler event
loop in one thread and your own select()/poll() in another thread.
Then, of course, you have the normal issues when doing multi-threading.

If you like, I can write an example on how to use add_iod() and friends
on your own.  It probably needs to be done.  But you may not need to,
you can do pretty much anything you need using the standard gensio
library.  You can open with a "dev" gensio, use it for I/O, and you can
get the file descriptor if you need to do ioctls.

-corey

**Comment by cminyard** [comment]
On Mon, Oct 09, 2023 at 12:51:36PM -0700, Eelco Chaudron wrote:
> The current code is rather old and has no event loop kind of interface. It is multithreaded though, so I could add some API around your event handler. I can do this in such a way a normal read/write/select, poll API will still work through a pipe to allow backward compatibility with both serial devices and gensio (without doing much re-design).

Ok.  In that case, you are better off just running an event loop in its
own thread.  Not hard to do.

> 
> I'm using ICANON mode, and sometimes I need to send data and wait for a reply synchronously with a timeout. Which will be tricky with an event loop.

Not really, the API has timers you can use.  If the event loop is
single-threaded, that's pretty simple.  If it's multi-threaded then
canceling the timer can be tricky, but that's about it.

-corey

**Comment by cminyard** [comment]
I've uploaded an example of using gensio with a poll() call in to the examples directory.  Hope this helps.

**Comment by chaudron** [comment]
Thanks a lot, this is the kind of thing I was planning to do. Ned to look at it more closely, especially the gensio APIs, but this will get me going. Will report back on what I did in the end, and might even send an MR to include is as an example (if it make sense).
