### ISSUE TITLE
 gensio_os_funcs_wake() not waiking up the waiter in another thread.

### ISSUE THREAD

**Issue by chaudron** [cminyard/gensio#67]
I'm doing some experimenting with the library, and I initialize the waiter and then start it in another thread.
Something like this:

```
static void vser_dummy_thread(void *args)
{
    int rc = gensio_os_funcs_wait(vser_os_funcs, vser_waiter, 1, NULL);
    printf("WAITER RETURN: %d\n", rc);
}
 
int main() {
...
   rc = gensio_default_os_hnd(0, &vser_os_funcs);
    if (rc) {
        err_str = "vser init could not allocate OS handler";
        goto rc_error_out;
    }

    gensio_os_funcs_set_vlog(vser_os_funcs, vser_vlog);

    rc = gensio_os_proc_setup(vser_os_funcs, &vser_proc_data);
    if (rc) {
        err_str = "vser could not setup process data";
        goto rc_error_out;
    }

    vser_waiter = gensio_os_funcs_alloc_waiter(vser_os_funcs);
    if (!vser_waiter) {
        err_str = "vser could not allocate waiter";
	rc = GE_NOMEM;
	goto rc_error_out;
    }

    rc = gensio_os_new_thread(vser_os_funcs, vser_dummy_thread, NULL,
                              &vser_tid);
    if (rc) {
        err_str = "vser could not initialize service thread";
	goto rc_error_out;
    }
```

The thread does not seem to return when calling `gensio_os_funcs_wake(vser_os_funcs, vser_waiter)` until there is some IO happening. Is this by design, or am I doing something wrong?

**Comment by cminyard** [comment]
On Oct 20, 2023 10:30 AM, Eelco Chaudron ***@***.***> wrote:
I'm doing some experimenting with the library, and I initialize the waiter and then start it in another thread.
Something like this:
static void vser_dummy_thread(void *args)
{
    int rc = gensio_os_funcs_wait(vser_os_funcs, vser_waiter, 1, NULL);
    printf("WAITER RETURN: %d\n", rc);
}
 
int main() {
...
   rc = gensio_default_os_hnd(0, &vser_os_funcs);
    if (rc) {
        err_str = "vser init could not allocate OS handler";
        goto rc_error_out;
    }

    gensio_os_funcs_set_vlog(vser_os_funcs, vser_vlog);

    rc = gensio_os_proc_setup(vser_os_funcs, &vser_proc_data);
    if (rc) {
        err_str = "vser could not setup process data";
        goto rc_error_out;
    }

    vser_waiter = gensio_os_funcs_alloc_waiter(vser_os_funcs);
    if (!vser_waiter) {
        err_str = "vser could not allocate waiter";
	rc = GE_NOMEM;
	goto rc_error_out;
    }

    rc = gensio_os_new_thread(vser_os_funcs, vser_dummy_thread, NULL,
                              &vser_tid);
    if (rc) {
        err_str = "vser could not initialize service thread";
	goto rc_error_out;
    }

The thread does not seem to return when calling gensio_os_funcs_wake(vser_os_funcs, vser_waiter) until there is some IO happening. Is this by design, or am I doing something wrong?I'm not really sure; that should work.  In fact, I'm working on Rust bindings and I have almost that exact code.  Can you send a complete program so I can run it?Thanks,-corey

**Comment by chaudron** [comment]
Find a sample that will compile with `gcc test.c -lgensio -lgensioosh -o test -Wall -Werror && ./test` and once you see 'WE WOKE UP THE THREAD" it will not return from the thread until enter is pressed.

This is the Fedora version I'm using: `libgensio-devel-2.7.5-1.fc38.x86_64`

```
#define _GNU_SOURCE   /* Needed  for asprintf() */
#include <errno.h>
#include <stdio.h>
#include <string.h>
#include <stdlib.h>
#include <unistd.h>
#include <stdint.h>
#include <stdbool.h>
#include <gensio/gensio.h>

static struct gensio_os_proc_data *vser_proc_data;
static struct gensio_os_funcs *vser_os_funcs;
static struct gensio_waiter *vser_waiter;
struct gensio_thread *vser_tid;

struct vser_fd {
    struct gensio *io;

} vser_fd_t;


static void vser_vlog(struct gensio_os_funcs *f, enum gensio_log_levels level,
                      const char *log, va_list args)
{
    /* For now we assume this log callback only gets called from the
     * dispatcher thread so no need to make this atomic for now.
     */
    fprintf(stderr, "vser[gensio] %s: ", gensio_log_level_to_str(level));
    vfprintf(stderr, log, args);
    fprintf(stderr, "\n");
}


static int vser_event_hanlder(struct gensio *io, void *user_data, int event,
                              int err, unsigned char *buf, gensiods *buflen,
                              const char *const *auxdata)
{
    printf("EVENT: %d, err = %d\n", event, err);

    switch(event) {

    case GENSIO_EVENT_READ:
        break;

    case GENSIO_EVENT_WRITE_READY:
        /* Nothing to transmit right now so disable the callback. */
        gensio_set_write_callback_enable(io, false);
        break;

    default:
        return GE_NOTSUP;
    }
    return 0;
}


static void vser_dummy_thread(void *args)
{
    int rc = gensio_os_funcs_wait(vser_os_funcs, vser_waiter, 1, NULL);
    printf("WAITER RETURN: %d\n", rc);
}

char *vser_init(void)
{
    /* This function will initialize the gensio library that will be used to
     * handle all the virtual (remote) serial ports. This will also start a
     * single thread that will run the gensio dispatcher to service all the
     * virtual serial ports.
     *
     * On success it will return NULL, on error an error string that needs
     * to be free()'ed.
     */
    char *err_str;
    char *out_err;
    int err;
    int rc;

    rc = gensio_default_os_hnd(0, &vser_os_funcs);
    if (rc) {
        err_str = "vser init could not allocate OS handler";
        goto rc_error_out;
    }

    gensio_os_funcs_set_vlog(vser_os_funcs, vser_vlog);

    rc = gensio_os_proc_setup(vser_os_funcs, &vser_proc_data);
    if (rc) {
        err_str = "vser could not setup process data";
        goto rc_error_out;
    }

    vser_waiter = gensio_os_funcs_alloc_waiter(vser_os_funcs);
    if (!vser_waiter) {
        err_str = "vser could not allocate waiter";
	rc = GE_NOMEM;
	goto rc_error_out;
    }

    rc = gensio_os_new_thread(vser_os_funcs, vser_dummy_thread, NULL,
                              &vser_tid);
    if (rc) {
        err_str = "vser could not initialize service thread";
	goto rc_error_out;
    }

    return NULL;

rc_error_out:
    if (vser_waiter)
        gensio_os_funcs_free_waiter(vser_os_funcs, vser_waiter);

    if (vser_proc_data)
        gensio_os_proc_cleanup(vser_proc_data);

    if (vser_os_funcs)
        gensio_os_funcs_free(vser_os_funcs);

    err = asprintf(&out_err, "%s: %s", err_str, gensio_err_to_str(rc));
    if (err == -1)
        return(strdup(err_str));

    return out_err;
}

char *vser_open(const char *pathname, struct vser_fd **fd)
{
    struct vser_fd *vfd;
    char *out_err;
    char *err_str;
    int err;
    int rc;

    if (!vser_os_funcs || !vser_waiter)
        return strdup("vser not initialized");

    if (pathname == NULL || strlen(pathname) == 0 || fd == NULL)
        return strdup("Invalid argument");

    vfd = calloc(1, sizeof(struct vser_fd));
    if (vfd == NULL)
        return strdup("Cannot allocate memory");

    rc = str_to_gensio("stdio(self)", vser_os_funcs, vser_event_hanlder,
                       vfd, &vfd->io);
    if (rc) {
  	err_str = "Could not initialize gensio device";
  	goto error_exit;
    }

    rc = gensio_open_s(vfd->io);
    if (rc) {
  	err_str = "Could not open gensio device";
  	goto error_exit;
      }

    gensio_set_write_callback_enable(vfd->io, true);
    gensio_set_read_callback_enable(vfd->io, true);

    *fd = vfd;
    return NULL;

error_exit:
    free(vfd);

    err = asprintf(&out_err, "%s: %s", err_str, gensio_err_to_str(rc));
    if (err == -1)
        return(strdup(err_str));

    *fd = NULL;
    return out_err;
}

int main()
{
    struct vser_fd *fd;
    char *err_str;

    printf("Starting!\n");
    err_str = vser_init();
    if (err_str) {
        printf("ERROR: %s\n", err_str);
        free(err_str);
        return 2;
    }

    err_str = vser_open("stdio(self)", &fd);
    if (err_str) {
        printf("ERROR: Can't open vser: %s\n", err_str);
        free(err_str);
        goto exit;
    }

    sleep(2);
    printf("END SLEEP!!\n");

exit:
    gensio_os_funcs_wake(vser_os_funcs, vser_waiter);
    printf("WE WOKE UP THE THREAD!!\n");
    gensio_os_wait_thread(vser_tid);

    return 0;
}
```

**Comment by cminyard** [comment]
Ah, I should have spotted this immediately.You need to tell the os handler what signal to use for waking other threads.  Usually SIGUSR1.  That's the first parameter to gensio_default_os_hnd().  Otherwise, it can't wake the other thread.-coreyOn Oct 21, 2023 10:20 AM, Eelco Chaudron ***@***.***> wrote:
Find a sample that will compile with gcc test.c -lgensio -lgensioosh -o test -Wall -Werror && ./test and once you see 'WE WOKE UP THE THREAD" it will not return from the thread until enter is pressed.
This is the Fedora version I'm using: libgensio-devel-2.7.5-1.fc38.x86_64
#define _GNU_SOURCE   /* Needed  for asprintf() */
#include <errno.h>
#include <stdio.h>
#include <string.h>
#include <stdlib.h>
#include <unistd.h>
#include <stdint.h>
#include <stdbool.h>
#include <gensio/gensio.h>

static struct gensio_os_proc_data *vser_proc_data;
static struct gensio_os_funcs *vser_os_funcs;
static struct gensio_waiter *vser_waiter;
struct gensio_thread *vser_tid;

struct vser_fd {
    struct gensio *io;

} vser_fd_t;


static void vser_vlog(struct gensio_os_funcs *f, enum gensio_log_levels level,
                      const char *log, va_list args)
{
    /* For now we assume this log callback only gets called from the
     * dispatcher thread so no need to make this atomic for now.
     */
    fprintf(stderr, "vser[gensio] %s: ", gensio_log_level_to_str(level));
    vfprintf(stderr, log, args);
    fprintf(stderr, "\n");
}


static int vser_event_hanlder(struct gensio *io, void *user_data, int event,
                              int err, unsigned char *buf, gensiods *buflen,
                              const char *const *auxdata)
{
    printf("EVENT: %d, err = %d\n", event, err);

    switch(event) {

    case GENSIO_EVENT_READ:
        break;

    case GENSIO_EVENT_WRITE_READY:
        /* Nothing to transmit right now so disable the callback. */
        gensio_set_write_callback_enable(io, false);
        break;

    default:
        return GE_NOTSUP;
    }
    return 0;
}


static void vser_dummy_thread(void *args)
{
    int rc = gensio_os_funcs_wait(vser_os_funcs, vser_waiter, 1, NULL);
    printf("WAITER RETURN: %d\n", rc);
}

char *vser_init(void)
{
    /* This function will initialize the gensio library that will be used to
     * handle all the virtual (remote) serial ports. This will also start a
     * single thread that will run the gensio dispatcher to service all the
     * virtual serial ports.
     *
     * On success it will return NULL, on error an error string that needs
     * to be free()'ed.
     */
    char *err_str;
    char *out_err;
    int err;
    int rc;

    rc = gensio_default_os_hnd(0, &vser_os_funcs);
    if (rc) {
        err_str = "vser init could not allocate OS handler";
        goto rc_error_out;
    }

    gensio_os_funcs_set_vlog(vser_os_funcs, vser_vlog);

    rc = gensio_os_proc_setup(vser_os_funcs, &vser_proc_data);
    if (rc) {
        err_str = "vser could not setup process data";
        goto rc_error_out;
    }

    vser_waiter = gensio_os_funcs_alloc_waiter(vser_os_funcs);
    if (!vser_waiter) {
        err_str = "vser could not allocate waiter";
	rc = GE_NOMEM;
	goto rc_error_out;
    }

    rc = gensio_os_new_thread(vser_os_funcs, vser_dummy_thread, NULL,
                              &vser_tid);
    if (rc) {
        err_str = "vser could not initialize service thread";
	goto rc_error_out;
    }

    return NULL;

rc_error_out:
    if (vser_waiter)
        gensio_os_funcs_free_waiter(vser_os_funcs, vser_waiter);

    if (vser_proc_data)
        gensio_os_proc_cleanup(vser_proc_data);

    if (vser_os_funcs)
        gensio_os_funcs_free(vser_os_funcs);

    err = asprintf(&out_err, "%s: %s", err_str, gensio_err_to_str(rc));
    if (err == -1)
        return(strdup(err_str));

    return out_err;
}

char *vser_open(const char *pathname, struct vser_fd **fd)
{
    struct vser_fd *vfd;
    char *out_err;
    char *err_str;
    int err;
    int rc;

    if (!vser_os_funcs || !vser_waiter)
        return strdup("vser not initialized");

    if (pathname == NULL || strlen(pathname) == 0 || fd == NULL)
        return strdup("Invalid argument");

    vfd = calloc(1, sizeof(struct vser_fd));
    if (vfd == NULL)
        return strdup("Cannot allocate memory");

    rc = str_to_gensio("stdio(self)", vser_os_funcs, vser_event_hanlder,
                       vfd, &vfd->io);
    if (rc) {
  	err_str = "Could not initialize gensio device";
  	goto error_exit;
    }

    rc = gensio_open_s(vfd->io);
    if (rc) {
  	err_str = "Could not open gensio device";
  	goto error_exit;
      }

    gensio_set_write_callback_enable(vfd->io, true);
    gensio_set_read_callback_enable(vfd->io, true);

    *fd = vfd;
    return NULL;

error_exit:
    free(vfd);

    err = asprintf(&out_err, "%s: %s", err_str, gensio_err_to_str(rc));
    if (err == -1)
        return(strdup(err_str));

    *fd = NULL;
    return out_err;
}

int main()
{
    struct vser_fd *fd;
    char *err_str;

    printf("Starting!\n");
    err_str = vser_init();
    if (err_str) {
        printf("ERROR: %s\n", err_str);
        free(err_str);
        return 2;
    }

    err_str = vser_open("stdio(self)", &fd);
    if (err_str) {
        printf("ERROR: Can't open vser: %s\n", err_str);
        free(err_str);
        goto exit;
    }

    sleep(2);
    printf("END SLEEP!!\n");

exit:
    gensio_os_funcs_wake(vser_os_funcs, vser_waiter);
    printf("WE WOKE UP THE THREAD!!\n");
    gensio_os_wait_thread(vser_tid);

    return 0;
}

**Comment by chaudron** [comment]
Thanks, that solved the problem!!
