### ISSUE TITLE
Packets sent to network in bursts with long delay

### ISSUE THREAD

**Issue by doaaron** [cminyard/gensio#68]
Hi. I installed ser2net on Ubuntu 22.04 using apt, and its showing version 4.3.4. I'm sending serial data to my PC and using the following ser2net settings. 

```
connection: &con0096
    accepter: udp,2000
    enable: on
    options:
      banner: *banner
      kickolduser: true
      telnet-brk-on-sync: true
    connector: serialdev,
              /dev/ttyUSB0,
              115200n82,local
```

The serial data is packets typically 40 bytes long (around 3 milliseconds) with 7 milliseconds spacing between packets and 115200 baud. I am able to send this stream over the network between PC1 and PC2, and I can capture the incoming and outgoing streams on my oscilloscope. Here are the serial port settings shown by stty 

```
speed 115200 baud; rows 0; columns 0; line = 0;
intr = <undef>; quit = <undef>; erase = <undef>; kill = <undef>; eof = <undef>; eol = <undef>; eol2 = <undef>; swtch = <undef>; start = ^Q;
stop = ^S; susp = <undef>; rprnt = <undef>; werase = <undef>; lnext = <undef>; discard = <undef>; min = 1; time = 0;
-parenb -parodd -cmspar cs8 -hupcl cstopb cread clocal -crtscts
ignbrk -brkint -ignpar -parmrk -inpck -istrip -inlcr -igncr -icrnl -ixon -ixoff -iuclc -ixany -imaxbel -iutf8
-opost -olcuc -ocrnl -onlcr -onocr -onlret -ofill -ofdel nl0 cr0 tab0 bs0 vt0 ff0
-isig -icanon -iexten -echo -echoe -echok -echonl -noflsh -xcase -tostop -echoprt -echoctl -echoke -flusho -extproc
```

The problem I'm seeing is that ser2net appears to buffer the serial data for around 100ms or so before putting it on the network. I verfied that ser2net is the source of the issue by running a wireshark capture on the ethernet port that ser2net directly puts data on. The UDP packets are properly split up, but they are being sent in bursts. See the example below. While the individual UDP packets are properly split up, they are coming in bursts instead of with the timing on the serial port. I have tried playing with some of ser2net's configuration options, but I haven't found anything that helps. 

Is this normal behavior, or perhaps a known issue? Thanks!

![Screenshot from 2023-11-10 12-01-07](https://github.com/cminyard/gensio/assets/10451207/a3c46472-3f47-4cb6-8e41-b55a00dd9aef)

**Comment by cminyard** [comment]
On Thu, Nov 09, 2023 at 03:03:19PM -0800, doaaron wrote:
> Hi. I installed ser2net on Ubuntu 22.04 using apt, and its showing version 4.3.4. I'm sending a serial data to my PC and using the following ser2net settings. 
> 
> ```
> connection: &con0096
>     accepter: udp,2000
>     enable: on
>     options:
>       banner: *banner
>       kickolduser: true
>       telnet-brk-on-sync: true
>     connector: serialdev,
>               /dev/ttyUSB0,
>               115200n82,local
> ```
> 
> The serial data is packets typically 40 bytes long (around 3 milliseconds) with 7 milliseconds spacing between packets and 115200 baud. I am able to send this stream over the network between PC1 and PC2, and I can capture the incoming and outgoing streams on my oscilloscope. 
> 
> The problem I'm seeing is that ser2net appears to buffer the serial data for around 100ms or so before putting it on the network. I verfied that ser2net is the source of the issue by running a wireshark capture on the ethernet port that ser2net directly puts data on. The UDP packets are properly split up, but they are being sent in bursts. See the example below. While the individual UDP packets are properly split up, they are coming in bursts instead of with the timing on the serial port. I have tried playing with some of ser2net's configuration options, but I haven't found anything that helps. 
> 
> Is this normal behavior, or perhaps a known issue? Thanks!

This is design intent, to improve network efficiency while giving
reasonable interactivity for humans.  When transferring a lot of data
the problem goes away, you get large buffers of data transferred
quickly.

The problem comes if you need quick turnaround on small packets.

You control this via two mechanisms:

* chardelay (and related values) in ser2net.yaml.  You can just add
  "chardelay: false" to the options to disable it, or you can adjust
  the timers.

* The Nagle algorithm.  This is on by default on TCP connections, you
  can disable it by adding "nodelay" to the tcp gensio options, like
  tcp(nodelay),<port>.

-corey

**Comment by doaaron** [comment]
Thanks for the reply. I've tried disabling chardelay, but I'm not seeing any difference. I'm also using UDP, so I guess the Nagle algorithm doesn't apply. Note that I'm using a USB to serial bridge from FTDI. I'm starting to wonder if it's the USB driver that's buffering the data.

**Comment by cminyard** [comment]
On Thu, Nov 09, 2023 at 04:40:55PM -0800, doaaron wrote:
> Thanks for the reply. I've tried disabling chardelay, but I'm not
> seeing any difference. I'm also using UDP, so I guess the Nagle
> algorithm doesn't apply. Note that I'm using a USB to serial bridge
> from FTDI. I'm starting to wonder if it's the USB driver that's
> buffering the data.

I kind of doubt it's the serial bridge.  But I'm not sure, I haven't
done that much testing with UDP.  I'll try to reproduce.

Can you try something different?  You can get the same type of thing
with gensiot, and it doesn't do anything special with delaying the data.
I believe the following will work:

  gensiot -i 'serialdev,/dev/ttyUSB0,115200n82,local' --server -a udp:2000

You don't get a banner or kickolduser or anything like that.  BTW,
telnet-brk-on-sync doesn't mean anything for a udp connection.

-corey

**Comment by cminyard** [comment]
On Thu, Nov 09, 2023 at 04:40:55PM -0800, doaaron wrote:
> Thanks for the reply. I've tried disabling chardelay, but I'm not seeing any difference. I'm also using UDP, so I guess the Nagle algorithm doesn't apply. Note that I'm using a USB to serial bridge from FTDI. I'm starting to wonder if it's the USB driver that's buffering the data.

I set something up to test this and I couldn't reproduce.  With
chardelay true (the default) it pasted together the data into one
packet.  With charedelay false it split up the packet.

I've reread what you said and it doesn't make sense that this is ser2net
doing it's chardelay.  If it was, the two packets would be squashed into
one packet.  I checked the serial port settings, and VMIN is 1 and VTIME
is 0, so that should be good.

What's a little more strange is that the packets are split up into
multiple UDP packets.  If they were really coming in one byte at a time,
they should be split up into smaller packets.  So I'm guessing there is
some buffering going on in the OS.  But that doesn't explain the 100ms.
I'm definitely not seeing that.

There is a tracing gensio that can help see where the problem is.  You
can change your connection definition to something like:
```
define: &banner Login banner
connection: &con0096
    accepter: trace(dir=write,file=udpside.txt),udp,2000
    enable: on
    options:
      banner: *banner
      kickolduser: true
      telnet-brk-on-sync: true
      chardelay: false
    connector: trace(dir=read,file=serialside.txt),serialdev,
              /dev/ttyPipeA3,
              115200n81,local
```
and you can look at the trace output from the trace files.  They are
timestamped with the system monotonic timer.

The other thing is that with something like this, it's really hard to
make any non-RT program run with the behavior you want.  You would at
least need chardelay set with the proper settings, not disabled.  It
might work most of the time, but it's really hard to guarantee.  If you
ran ser2net as an RT process and set up chardelay, it might work.

-corey

**Comment by doaaron** [comment]
Thanks for the help on this Corey. 

1. So first I tested the gensiot command you provided. This turned out to be worse as I still saw the ~100ms build up between sends, but this time I was getting one big UDP packet instead of multiple small ones. Ready through your documentation of chardelay for ser2net, I'm pretty sure it is required to split the UDP packets properly, and it's doing it's job. The problem I'm seeing is these UDP packets are bundled together instead of properly spaced.
2. I then went on to do the tracing you mentioned. This is an excerpt for what I see on the serial side (only the timestamp shown)

```
255318:402932 Read (64):
255318:403142 Read (64):
255318:403310 Read (64):
255318:403486 Read (64):
255318:403647 Read (64):
255318:403805 Read (64):
255318:403964 Read (48):
255318:514324 Read (64):
255318:514605 Read (64):
255318:514780 Read (64):
255318:514954 Read (64):
255318:515133 Read (64):
255318:515283 Read (64):
255318:515427 Read (64):
255318:515600 Read (48):
255318:625861 Read (64):
255318:626095 Read (64):
255318:626261 Read (64):
255318:626433 Read (64):
255318:626610 Read (64):
255318:626764 Read (64):
255318:626914 Read (64):
255318:627078 Read (48):
255318:737606 Read (64):
255318:737839 Read (64):
255318:738050 Read (64):
255318:738234 Read (64):
255318:738423 Read (64):
255318:738576 Read (64):
255318:738741 Read (64):
255318:738890 Read (48):
255318:766636 Read (64):
255318:766719 Read (59):
255318:794752 Read (64):
255318:794983 Read (59):
255318:810757 Read (61):
```
I'm assuming that the format is seconds:microseconds. Here you can clearly see the packets getting bundled together. So I assume that means the issue is coming from my USB to serial bridge?

**Comment by cminyard** [comment]
On Sun, Nov 12, 2023 at 01:27:25PM -0800, doaaron wrote:
> Thanks for the help on this Corey. 

No problem.  We've elmimated ser2net as the issue, it appears, which
unfortunately means there's not much I can do to help you :-(.

> 
> 255318:738890 Read (48):
> 255318:766636 Read (64):
> 255318:766719 Read (59):
> 255318:794752 Read (64):
> 255318:794983 Read (59):
> 255318:810757 Read (61):
> ```
> I'm assuming that the format is seconds:microseconds.

Correct

> Here you can clearly see the packets getting bundled together. So I assume that means the issue is coming from my USB to serial bridge? 

Either that, or the driver, or just the slowness of the system.

The hardware will queue to a point until the driver picks up the data,
and the driver will queue until userspace picks up the data.

You can try running ser2net as an RT program:
  chrt --fifo 10 ser2net ...
But I'm guessing, from the consistency of what you are seeing, that it
won't help.  I would guess either the hardware is doing this or the
driver is polling for data.

-corey

**Comment by doaaron** [comment]
I think the root cause was actually the USB-serial IC. It is optimized for USB throughput, so it helpfully buffers data and sends it bundled together to the host. In case anybody is interested, here is the App note from FTDI which describes this behavior

https://www.ftdichip.com/Documents/AppNotes/AN232B-04_DataLatencyFlow.pdf

This thread actually describes how you can adjust the chipset latency 

https://askubuntu.com/questions/696593/reduce-request-latency-on-an-ftdi-ubs-to-rs-232-adapter

Directly setting the latency through the sysfs wasn't possible on my system, but this thread provided a solution

https://www.reddit.com/r/Ubuntu/comments/i3o7zd/comment/g0ct1ig/

With the low latency setting enabled, the data isn't _as_ bundled together, but I'm still seeing up to 35ms of delay. I'm guessing there might be some optimization through the App Note, but as you mentioned, Linux is not an RT system, so there's a limit to what I'm going to be able to achieve. 

Thanks again for the help. I'll close this issue now.
